### PR TITLE
Dockerisation of BE and FE

### PR DESCRIPTION
**Pull request by aliL2000**
This PR dockerises and modifies the structure so that we can get both BE and FE working on the docker containers

### CODE REVIEW

**Comment by thenewguy321** [comment]
Close #8

**Comment by Brenden-Trieu** [comment]
Close #29

**Review by Brenden-Trieu — APPROVED** [review]
All good to me and I know it works so good to merge

**Review by yuqi88 — APPROVED** [review]
LGTM

**Review by Jeena01 — APPROVED** [review]
LGTM!

**Pull request merged**
