### PR TITLE
Docker fronted setup

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
Dockerization complete for frontend and updated readme for commands on running it

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
Close #6

**Review by thenewguy321 — APPROVED** [review]
Changes look good to me!

**Comment by Brenden-Trieu** [comment]
Keep in mind this is just the docker setup for the current frontend.

The backend and DB will be in a separate container

**Comment by Jeena01** [comment]
LGTM!

**Review by Jeena01 — APPROVED** [review]
thank you for setting this up!

**Pull request merged**
