### PR TITLE
BE Support for Video Upload

### PR DESCRIPTION
**Pull request by aliL2000**
PR that creates BE functionality for user to upload an image an save it on default db

It is currently being worked on, DO NOT MERGE the PR yet, as development is continuing

### CODE REVIEW

**Comment by yuqi88** [comment]
@aliL2000 if you have some PR not ready but you want the PR up, there's an option to make the PR a draft

**Comment by aliL2000** [comment]
Added these changes as a result of this video: https://www.youtube.com/watch?v=aR_JzBGdGvM&t=745s&ab_channel=BLearningClub

**Comment by aliL2000** [comment]
Good to merge PR now

**Comment by Brenden-Trieu** [comment]
I'm under the assumption that the backend work now right? and these changes don't cause any errors

**Comment by aliL2000** [comment]
> I'm under the assumption that the backend work now right? and these changes don't cause any errors

BE is working now

**Review by Brenden-Trieu — APPROVED** [review]
Backend works so all good to me

**Pull request merged**
