### PR TITLE
added styles

### PR DESCRIPTION
**Pull request by Jeena01**
added scss files

### CODE REVIEW

**Comment by Jeena01** [comment]
this commit has the styling and the step instructions

**Comment by Jeena01** [comment]
closes #57

**Review by aliL2000 — APPROVED** [review]
Changes look good to me

**Review by Brenden-Trieu — APPROVED** [review]

**Comment by yuqi88** [comment]
Lgmt!

**Comment by yuqi88** [comment]
@everyone we should be on the same page for using sass and not css. If we need a discussion about this, next team meeting.

**Pull request merged**
