### PR TITLE
Button routing

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
Button routes to WIP stepper page

App currently shows a blank page that will be made into a newly designed home splash page for the Rosen app

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
Close #38

**Review by Jeena01 — APPROVED** [review]
LGTM thank you for the work

**Review by yuqi88 — APPROVED** [review]
Awesome!
Thank you for the routing!

**Comment by aliL2000** [comment]
Review not needed, but changes look good to me

**Pull request merged**
