### PR TITLE
Frontend rename

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
Renames the frontend ONLY

has been tested and functions correctly

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
To be merged AFTER #28

**Comment by Brenden-Trieu** [comment]
Close #30

**Review by aliL2000 — APPROVED** [review]
Changes look good to me

**Review by yuqi88 — APPROVED** [review]
LGTM

**Review by Jeena01 — APPROVED** [review]
love the new names

**Pull request merged**
