### PR TITLE
Client Meeting Notes W13

### PR DESCRIPTION
**Pull request by aliL2000**
Adding client meeting notes for this week to repo

### CODE REVIEW

**Review by Jeena01 — APPROVED** [review]
lgtm!

**Comment by aliL2000** [comment]
Close #70

**Review by Brenden-Trieu — APPROVED** [review]
Looks good

**Comment by Brenden-Trieu** [comment]
If I am correct for the next client meeting, we are setting up a remote desktop so he can try the current build right?

**Comment by yuqi88** [comment]
Lgtm

**Pull request merged**
