### PR TITLE
making the app pretty for the demo

### PR DESCRIPTION
**Pull request by Jeena01**

### CODE REVIEW

**Review by aliL2000 — APPROVED** [review]
Changes look good to me!

**Comment by Jeena01** [comment]
image

**Comment by Jeena01** [comment]
image

**Comment by Jeena01** [comment]
closes #61

**Review by yuqi88 — APPROVED** [review]
We should have a PR in the future to use the step_intructions.json and not copy and paste them in the stepper component. But for now, it's good

**Pull request merged**
