### PR TITLE
Integrate frontend - demo purpose (only?)

### LINKED ISSUE #65: Intergration for demo

### PR DESCRIPTION
**Pull request by yuqi88**
This is messy. Cleaning this branch and discussion should be our very next tasks before adding any other features.

closes #65

### CODE REVIEW

**Comment by yuqi88** [comment]
Home page:
image

Step page:
image

step2:
image

step3:
image

step4:
image

**Comment by yuqi88** [comment]
There are some styling errors here, but we can fix them tomorrow.

**Review by Brenden-Trieu — APPROVED** [review]
All works and will be the current build for frontend

**Comment by aliL2000** [comment]
Changes do look good to me, and have tested on personal device

**Comment by Brenden-Trieu** [comment]
Work still left to do in frontend:
- Loading screen/status
- proper home page
- colour correction (cohesion)
- Login (?)
- all of step 5
- other suggestions from peer testing...

**Comment by Brenden-Trieu** [comment]
We may also want to change the colouring of the stepper buttons to align with other generally used colours

**Pull request merged**
