### PR TITLE
Button component template creation

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
Working button component 

Needs to be tested with applicable frontend code, but structure is complete

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
image

**Comment by yuqi88** [comment]
For future branches, please screenshot what it looks like because we don't run the code, and we don't know what it looks like. Thanks.

**Review by thenewguy321 — APPROVED** [review]
The changes look good to me

**Comment by Brenden-Trieu** [comment]
Close #19

**Review by thenewguy321 — APPROVED** [review]
Changes look good to me

**Comment by yuqi88** [comment]
look good to me for now. 
(1) The styles (the look of the button) we will modify in the future.
(2) The style codes should be moved to other css or scss file in the future.

**Review by yuqi88 — APPROVED** [review]
GJ

**Comment by Jeena01** [comment]
LGTM!

**Review by Jeena01 — APPROVED** [review]
thank you

**Pull request merged**
