### PR TITLE
Reorganization and page creation

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
Reorganized Frontend folders to be appropriate for convention, made pages and converted Frontend to TypeScript

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
Close #36

**Comment by Brenden-Trieu** [comment]
Close #50

**Comment by yuqi88** [comment]
In the future, we should separate the styling codes (.scss file) from the component code (.jxs)

**Review by yuqi88 — APPROVED** [review]
LGTM!

**Pull request merged**
